# Generated by Django 5.1.6 on 2025-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('folio_inicial', models.CharField(max_length=50)),
                ('folio_final', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100)),
                ('subserie', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Indefinido', 'Indefinido'), ('Finalizado', 'Finalizado')], max_length=20)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
