# Generated by Django 5.1.6 on 2025-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='folio_final',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='folio_inicial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='hash_sha256',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('Factura', 'Factura'), ('Contrato', 'Contrato'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
