# Generated by Django 5.1.6 on 2025-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_remove_documento_ruta_archivo_documento_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ruta_fisica',
            field=models.CharField(blank=True, help_text='Ingrese la ubicación física real del documento (ej. "Módulo 2, Caja 5, Carpeta 12")', max_length=255, null=True, verbose_name='Ruta física'),
        ),
    ]
