# Generated by Django 5.1.6 on 2025-02-12 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='documentos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='monitoreo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ruta_fisica',
            field=models.CharField(blank=True, help_text='Ej. Módulo 2, Caja 5, Carpeta 12', max_length=255, null=True, verbose_name='Ruta física'),
        ),
    ]
