# Generated by Django 5.1.6 on 2025-02-12 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='tipo_documento',
            new_name='tipo_documental',
        ),
        migrations.AddField(
            model_name='documento',
            name='sesion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sesión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='subsesion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-sesión'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código sólo puede contener números y puntos (por ejemplo, 100.02.01).', regex='^[0-9\\.]+$')]),
        ),
    ]
