# Generated by Django 5.1.6 on 2025-02-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_rename_tipo_documento_documento_tipo_documental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRDRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. 100.02.06', max_length=50, unique=True)),
                ('sesion', models.CharField(help_text='Ej. Gerencia o Dirección Administrativa', max_length=100)),
                ('subsesion', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(help_text='Ej. ACTAS, CONTRATOS, etc.', max_length=100)),
                ('subserie', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documental', models.CharField(help_text='Ej. Acta, Contrato, Informe, etc.', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción (opcional)', null=True)),
            ],
        ),
    ]
