# Generated by Django 5.1.6 on 2025-03-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_alter_documento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documental',
            field=models.CharField(choices=[('Acta', 'Acta'), ('Circular', 'Circular'), ('Informe', 'Informe'), ('Instrumento', 'Instrumento'), ('Proyecto', 'Proyecto'), ('Publicación', 'Publicación'), ('Factura', 'Factura'), ('Contrato', 'Contrato'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
