# Generated by Django 5.1.6 on 2025-04-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_documento_activo_alter_documento_tipo_documental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='hash_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
