# Generated by Django 5.1.6 on 2025-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_trdregistro_anios_central_trdregistro_anios_gestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='anios_central',
            field=models.PositiveIntegerField(default=0, verbose_name='Años de Archivo Central'),
        ),
        migrations.AddField(
            model_name='documento',
            name='anios_gestion',
            field=models.PositiveIntegerField(default=0, verbose_name='Años de Gestión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='disposicion_final',
            field=models.CharField(blank=True, max_length=50, verbose_name='Disposición Final'),
        ),
    ]
