# Generated by Django 5.1.6 on 2025-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_documento_anios_central_documento_anios_gestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='anios_central',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='anios_gestion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='disposicion_final',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='estado',
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documental',
            field=models.CharField(max_length=50),
        ),
    ]
