# Generated by Django 5.1.6 on 2025-04-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0014_remove_documento_anios_central_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trdregistro',
            name='disposicion_final',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
