# Generated by Django 5.1.6 on 2025-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Basico', 'Basico')], default='Administrador', max_length=20),
        ),
    ]
